### ISSUE TITLE
Support configuring Kafka bootstrap servers both from a single server or multiple servers

### ISSUE THREAD

**Issue by smoya** [asyncapi/event-gateway#57]
Current configuration is limited to just one server, which is used as Kafka bootstrap server. For example:

```yaml
servers:
    asyncapi-kafka-test:
        url: 'asyncapi-kafka-test-asyncapi-8f90.aivencloud.com:20472'
        protocol: kafka-secure
```

The event-gateway gets the value of `url` field and uses it as the **only Kafka bootstrap server**, mapping it to the same port but locally, meaning `:20472` (can be changed through extension). Then it opens a new local port dynamically for each discovered broker (if there are).

However, users might want to configure several Kafka bootstrap servers (actually recommended).

There are several possibilities:

## 1. To group servers of the same cluster
There is a RFC0 implementation for this: https://github.com/asyncapi/spec/issues/465.

We could support it from day one via extensions: `x-cluster` field or similar. Or rather add it as official change in the [Kafka binding](https://github.com/asyncapi/bindings/tree/master/kafka).

## 2. To add a new extension to the existing server

Support only one server, and add the rest of bootstrap servers in a new extension like `x-extra-bootstrap-servers`.

I'm completely leaning towards the first. But open to suggestions.
